backend:
    # name: git-gateway
    name: github
    repo: AsMuin/AsMuin_WebSite
    branch: edit # Branch to update (optional; defaults to master)
    i18n: true
media_folder: 'img/uploads' # Media files will be stored in the repo under images/uploads
collections:
    - name: 'blog' # Used in routes, e.g., /admin/collections/blog
      label: '随记' # Used in the UI
      folder: '/blog' # The path to the folder where the documents are stored
      filter: { field: 'language', value: 'cn' }
      create: true # Allow users to create new documents in this collection
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
          - { label: '标题', name: 'title', widget: 'string' }
          - {
                label: '作者',
                name: 'authors',
                widget: 'list',
                default: ['AsMuin']
            }
          - { label: '发布日期', name: 'date', widget: 'datetime' }
          - { label: '标签', name: 'tags', widget: 'list' }
          - { label: '正文', name: 'body', widget: 'markdown' }
